# Generated by Django 3.2.9 on 2022-01-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_delete_patientprescriptiondetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPrescriptionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicineName', models.CharField(max_length=100)),
                ('noOfTime', models.PositiveIntegerField()),
                ('noOfTablets', models.PositiveIntegerField()),
                ('syrupsQuantity', models.PositiveIntegerField()),
                ('test', models.CharField(max_length=100)),
            ],
        ),
    ]
