# Generated by Django 3.2.9 on 2022-01-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_patientprescriptiondetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprescriptiondetails',
            name='patientId',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
